[2025-06-30T18:28:44.259+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-30T18:28:44.423+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_python_dependencies_v02.get_matplotlib scheduled__2022-04-18T00:00:00+00:00 [queued]>
[2025-06-30T18:28:44.501+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_python_dependencies_v02.get_matplotlib scheduled__2022-04-18T00:00:00+00:00 [queued]>
[2025-06-30T18:28:44.502+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-06-30T18:28:44.606+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): get_matplotlib> on 2022-04-18 00:00:00+00:00
[2025-06-30T18:28:44.674+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_dependencies_v02', 'get_matplotlib', 'scheduled__2022-04-18T00:00:00+00:00', '--job-id', '6045', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_python_dependencies.py', '--cfg-path', '/tmp/tmpx_1xj8rf']
[2025-06-30T18:28:44.680+0000] {standard_task_runner.py:91} INFO - Job 6045: Subtask get_matplotlib
[2025-06-30T18:28:44.679+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4378) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-30T18:28:44.696+0000] {standard_task_runner.py:63} INFO - Started process 4382 to run task
[2025-06-30T18:28:44.843+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_python_dependencies_v02.get_matplotlib scheduled__2022-04-18T00:00:00+00:00 [running]> on host 98bcb8e24950
[2025-06-30T18:28:45.324+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='shivanshu' AIRFLOW_CTX_DAG_ID='dag_with_python_dependencies_v02' AIRFLOW_CTX_TASK_ID='get_matplotlib' AIRFLOW_CTX_EXECUTION_DATE='2022-04-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-04-18T00:00:00+00:00'
[2025-06-30T18:28:45.325+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-30T18:28:45.371+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-30T18:28:45.372+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 20, in get_matplotlib
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2025-06-30T18:28:45.420+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=dag_with_python_dependencies_v02, task_id=get_matplotlib, execution_date=20220418T000000, start_date=20250630T182844, end_date=20250630T182845
[2025-06-30T18:28:45.651+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 6045 for task get_matplotlib (No module named 'matplotlib'; 4382)
[2025-06-30T18:28:45.747+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-30T18:28:45.830+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-30T18:28:45.836+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
