[2025-06-30T18:26:48.616+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-30T18:26:48.698+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_python_dependencies_v02.get_matplotlib scheduled__2022-02-07T00:00:00+00:00 [queued]>
[2025-06-30T18:26:48.712+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_python_dependencies_v02.get_matplotlib scheduled__2022-02-07T00:00:00+00:00 [queued]>
[2025-06-30T18:26:48.713+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-06-30T18:26:48.747+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): get_matplotlib> on 2022-02-07 00:00:00+00:00
[2025-06-30T18:26:48.776+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_dependencies_v02', 'get_matplotlib', 'scheduled__2022-02-07T00:00:00+00:00', '--job-id', '5900', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_python_dependencies.py', '--cfg-path', '/tmp/tmpmacshbf9']
[2025-06-30T18:26:48.786+0000] {standard_task_runner.py:91} INFO - Job 5900: Subtask get_matplotlib
[2025-06-30T18:26:48.826+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3653) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-30T18:26:48.828+0000] {standard_task_runner.py:63} INFO - Started process 3658 to run task
[2025-06-30T18:26:48.898+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_python_dependencies_v02.get_matplotlib scheduled__2022-02-07T00:00:00+00:00 [running]> on host 98bcb8e24950
[2025-06-30T18:26:49.082+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='shivanshu' AIRFLOW_CTX_DAG_ID='dag_with_python_dependencies_v02' AIRFLOW_CTX_TASK_ID='get_matplotlib' AIRFLOW_CTX_EXECUTION_DATE='2022-02-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-02-07T00:00:00+00:00'
[2025-06-30T18:26:49.083+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-30T18:26:49.108+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-30T18:26:49.109+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 20, in get_matplotlib
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2025-06-30T18:26:49.124+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=dag_with_python_dependencies_v02, task_id=get_matplotlib, execution_date=20220207T000000, start_date=20250630T182648, end_date=20250630T182649
[2025-06-30T18:26:49.148+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5900 for task get_matplotlib (No module named 'matplotlib'; 3658)
[2025-06-30T18:26:49.170+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-30T18:26:49.206+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-30T18:26:49.208+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
