[2025-06-30T18:31:12.931+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-30T18:31:13.043+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_python_dependencies_v02.get_sklearn scheduled__2022-07-22T00:00:00+00:00 [queued]>
[2025-06-30T18:31:13.080+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_python_dependencies_v02.get_sklearn scheduled__2022-07-22T00:00:00+00:00 [queued]>
[2025-06-30T18:31:13.080+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-06-30T18:31:13.171+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): get_sklearn> on 2022-07-22 00:00:00+00:00
[2025-06-30T18:31:13.199+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_dependencies_v02', 'get_sklearn', 'scheduled__2022-07-22T00:00:00+00:00', '--job-id', '6230', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_python_dependencies.py', '--cfg-path', '/tmp/tmpz715nswc']
[2025-06-30T18:31:13.203+0000] {standard_task_runner.py:91} INFO - Job 6230: Subtask get_sklearn
[2025-06-30T18:31:13.210+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=5273) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-30T18:31:13.212+0000] {standard_task_runner.py:63} INFO - Started process 5280 to run task
[2025-06-30T18:31:13.355+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_python_dependencies_v02.get_sklearn scheduled__2022-07-22T00:00:00+00:00 [running]> on host 98bcb8e24950
[2025-06-30T18:31:14.001+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='shivanshu' AIRFLOW_CTX_DAG_ID='dag_with_python_dependencies_v02' AIRFLOW_CTX_TASK_ID='get_sklearn' AIRFLOW_CTX_EXECUTION_DATE='2022-07-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-07-22T00:00:00+00:00'
[2025-06-30T18:31:14.006+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-30T18:31:14.543+0000] {local_task_job_runner.py:124} ERROR - Received SIGTERM. Terminating subprocesses
[2025-06-30T18:31:14.689+0000] {process_utils.py:132} INFO - Sending 15 to group 5280. PIDs of all processes in the group: [5280]
[2025-06-30T18:31:14.689+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 5280
[2025-06-30T18:31:14.692+0000] {taskinstance.py:2607} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-06-30T18:31:14.707+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-30T18:31:14.891+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 15, in get_sklearn
    import sklearn
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/__init__.py", line 73, in <module>
    from .base import clone  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 19, in <module>
    from .utils._metadata_requests import _MetadataRequester, _routing_enabled
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/__init__.py", line 9, in <module>
    from ._chunking import gen_batches, gen_even_slices
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_chunking.py", line 11, in <module>
    from ._param_validation import Interval, validate_params
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 17, in <module>
    from .validation import _is_arraylike_not_scalar
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 15, in <module>
    import joblib
  File "/home/airflow/.local/lib/python3.12/site-packages/joblib/__init__.py", line 116, in <module>
    from ._store_backends import StoreBackendBase
  File "/home/airflow/.local/lib/python3.12/site-packages/joblib/_store_backends.py", line 20, in <module>
    from .logger import format_time
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 921, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 819, in module_from_spec
  File "<frozen importlib._bootstrap>", line 798, in _init_module_attrs
  File "<frozen importlib._bootstrap>", line 638, in cached
  File "<frozen importlib._bootstrap_external>", line 614, in _get_cached
  File "<frozen importlib._bootstrap_external>", line 508, in cache_from_source
  File "<frozen importlib._bootstrap_external>", line 134, in _path_split
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2609, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-06-30T18:31:14.990+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=dag_with_python_dependencies_v02, task_id=get_sklearn, execution_date=20220722T000000, start_date=20250630T183113, end_date=20250630T183114
[2025-06-30T18:31:15.298+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=5280, status='terminated', exitcode=2, started='18:31:12') (5280) terminated with exit code 2
[2025-06-30T18:31:15.300+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 143
[2025-06-30T18:31:15.347+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-30T18:31:17.759+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
